"""Tool catalog with param schemas for the web UI frontend form generation."""

from __future__ import annotations

from typing import Any

# -- Param helpers --


def _p(name: str, typ: str, required: bool = True, description: str = "", **kw: Any) -> dict[str, Any]:
    d: dict[str, Any] = {"name": name, "type": typ, "required": required, "description": description}
    d.update(kw)
    return d


def _pid(required: bool = True) -> dict[str, Any]:
    return _p("presentation_id", "uuid", required, "Session UUID", auto_fill="presentation_id")


def _si() -> dict[str, Any]:
    return _p("slide_index", "number", True, "1-based slide index")


def _shape_id_pair() -> list[dict[str, Any]]:
    return [
        _p("shape_name", "string", False, "Shape name"),
        _p("shape_id", "number", False, "Shape ID (alternative to shape_name)"),
    ]


# -- Catalog --

TOOL_CATALOG: list[dict[str, Any]] = [
    # === Session ===
    {
        "name": "pptx_get_engine_info",
        "description": "Return active engine mode and runtime details.",
        "category": "Session",
        "mutating": False,
        "params": [],
    },
    {
        "name": "pptx_create_presentation",
        "description": "Create a new in-memory session.",
        "category": "Session",
        "mutating": True,
        "params": [
            _p("width", "measurement", False, "Slide width, e.g. '10in'", placeholder="10in"),
            _p("height", "measurement", False, "Slide height, e.g. '7.5in'", placeholder="7.5in"),
            _p("template_path", "path", False, "Absolute .potx/.pptx template path"),
        ],
    },
    {
        "name": "pptx_open_presentation",
        "description": "Open an existing .pptx into a safe working copy.",
        "category": "Session",
        "mutating": True,
        "params": [
            _p("file_path", "path", True, "Absolute path to .pptx file"),
        ],
    },
    {
        "name": "pptx_save_presentation",
        "description": "Persist working copy to an output path.",
        "category": "Session",
        "mutating": True,
        "params": [
            _pid(),
            _p("output_path", "path", True, "Absolute output .pptx path"),
        ],
    },
    {
        "name": "pptx_close_presentation",
        "description": "Close a presentation session.",
        "category": "Session",
        "mutating": True,
        "params": [_pid()],
    },
    {
        "name": "pptx_list_open_presentations",
        "description": "List all open presentation sessions.",
        "category": "Session",
        "mutating": False,
        "params": [],
    },
    {
        "name": "pptx_get_presentation_state",
        "description": "Return slide index, titles, layouts, and shape counts.",
        "category": "Session",
        "mutating": False,
        "params": [_pid()],
    },
    # === Discovery ===
    {
        "name": "pptx_get_layouts",
        "description": "Discover available layout names and placeholder types.",
        "category": "Discovery",
        "mutating": False,
        "params": [_pid()],
    },
    {
        "name": "pptx_get_layout_detail",
        "description": "Return full placeholder inventory for a named layout.",
        "category": "Discovery",
        "mutating": False,
        "params": [
            _pid(),
            _p("layout_name", "string", True, "Exact layout name from pptx_get_layouts"),
        ],
    },
    {
        "name": "pptx_get_masters",
        "description": "List slide masters available in the presentation.",
        "category": "Discovery",
        "mutating": False,
        "params": [_pid()],
    },
    {
        "name": "pptx_get_theme",
        "description": "Return theme colors and font scheme.",
        "category": "Discovery",
        "mutating": False,
        "params": [_pid()],
    },
    # === Slides ===
    {
        "name": "pptx_get_slide",
        "description": "Return complete slide shape tree, placeholders, and notes.",
        "category": "Slides",
        "mutating": False,
        "params": [_pid(), _si()],
    },
    {
        "name": "pptx_add_slide",
        "description": "Add a slide by exact layout name.",
        "category": "Slides",
        "mutating": True,
        "params": [
            _pid(),
            _p("layout_name", "string", True, "Layout name from pptx_get_layouts"),
            _p("position", "number", False, "1-based insertion position"),
        ],
    },
    {
        "name": "pptx_duplicate_slide",
        "description": "Duplicate an existing slide.",
        "category": "Slides",
        "mutating": True,
        "params": [
            _pid(),
            _p("source_index", "number", True, "1-based source slide index"),
            _p("target_position", "number", False, "Optional target position"),
        ],
    },
    {
        "name": "pptx_delete_slide",
        "description": "Delete a slide by index.",
        "category": "Slides",
        "mutating": True,
        "params": [_pid(), _si()],
    },
    {
        "name": "pptx_reorder_slides",
        "description": "Reorder slides using full desired order list.",
        "category": "Slides",
        "mutating": True,
        "params": [
            _pid(),
            _p("new_order", "array", True, "Array of 1-based indices, e.g. [2,1,3]", placeholder="[2, 1, 3]"),
        ],
    },
    {
        "name": "pptx_move_slide",
        "description": "Move one slide from one index to another.",
        "category": "Slides",
        "mutating": True,
        "params": [
            _pid(),
            _p("from_index", "number", True, "Source index"),
            _p("to_index", "number", True, "Target index"),
        ],
    },
    {
        "name": "pptx_set_slide_background",
        "description": "Set slide background: solid color, image, or gradient.",
        "category": "Slides",
        "mutating": True,
        "params": [
            _pid(),
            _si(),
            _p("color_hex", "string", False, "Hex color RRGGBB"),
            _p("image_path", "path", False, "Absolute image path"),
            _p("gradient_start_color_hex", "string", False, "Gradient start color"),
            _p("gradient_end_color_hex", "string", False, "Gradient end color"),
        ],
    },
    {
        "name": "pptx_get_slide_snapshot",
        "description": "Return Base64 JPEG preview of a slide.",
        "category": "Slides",
        "mutating": False,
        "params": [
            _pid(),
            _si(),
            _p("width_px", "number", False, "Width in pixels (128-4096)"),
        ],
    },
    {
        "name": "pptx_get_slide_text",
        "description": "Extract ALL text from a slide.",
        "category": "Slides",
        "mutating": False,
        "params": [_pid(), _si()],
    },
    {
        "name": "pptx_get_slide_xml",
        "description": "Return raw OOXML content of a slide.",
        "category": "Slides",
        "mutating": False,
        "params": [_pid(), _si()],
    },
    {
        "name": "pptx_set_slide_notes",
        "description": "Write or replace speaker notes.",
        "category": "Slides",
        "mutating": True,
        "params": [
            _pid(),
            _si(),
            _p("notes_text", "string", True, "Notes text content"),
        ],
    },
    {
        "name": "pptx_find_replace_text",
        "description": "Find and replace text across slides.",
        "category": "Slides",
        "mutating": True,
        "params": [
            _pid(),
            _p("find_text", "string", True, "Text to find"),
            _p("replace_text", "string", True, "Replacement text"),
            _p("case_sensitive", "boolean", False, "Default true"),
            _p("slide_indices", "array", False, "Limit to specific slides", placeholder="[1, 2]"),
        ],
    },
    {
        "name": "pptx_add_connector",
        "description": "Add a connecting line that snaps to shapes.",
        "category": "Slides",
        "mutating": True,
        "params": [
            _pid(),
            _si(),
            _p("connector_type", "enum", False, "Connector type", enum_values=["straight", "elbow", "curve"]),
            _p("begin_shape_name", "string", False, "Begin shape name"),
            _p("begin_shape_id", "number", False, "Begin shape ID"),
            _p("begin_connection_site", "number", False, "Begin connection site (0-3)"),
            _p("end_shape_name", "string", False, "End shape name"),
            _p("end_shape_id", "number", False, "End shape ID"),
            _p("end_connection_site", "number", False, "End connection site (0-3)"),
            _p("color_hex", "string", False, "Line color hex"),
            _p("width_pt", "number", False, "Line width in points"),
        ],
    },
    # === Placeholders ===
    {
        "name": "pptx_get_placeholders",
        "description": "List placeholders with names, types, and geometry.",
        "category": "Placeholders",
        "mutating": False,
        "params": [_pid(), _si()],
    },
    {
        "name": "pptx_set_placeholder_text",
        "description": "Inject text into a placeholder by name.",
        "category": "Placeholders",
        "mutating": True,
        "params": [
            _pid(),
            _si(),
            _p("placeholder_name", "string", True, "Placeholder name"),
            _p("text_content", "string", True, "Text content"),
            _p("alignment", "enum", False, "Text alignment", enum_values=["left", "center", "right", "justify"]),
            _p("font_name", "string", False, "Font name"),
            _p("font_size_pt", "number", False, "Font size in points"),
            _p("bold", "boolean", False, "Bold"),
            _p("italic", "boolean", False, "Italic"),
            _p("underline", "boolean", False, "Underline"),
            _p("color_hex", "string", False, "Font color hex"),
        ],
    },
    {
        "name": "pptx_set_placeholder_image",
        "description": "Set a placeholder image from file path.",
        "category": "Placeholders",
        "mutating": True,
        "params": [
            _pid(),
            _si(),
            _p("placeholder_name", "string", True, "Placeholder name"),
            _p("image_path", "path", True, "Absolute image path"),
        ],
    },
    {
        "name": "pptx_clear_placeholder",
        "description": "Clear content of a placeholder.",
        "category": "Placeholders",
        "mutating": True,
        "params": [
            _pid(),
            _si(),
            _p("placeholder_name", "string", True, "Placeholder name"),
        ],
    },
    {
        "name": "pptx_get_placeholder_text",
        "description": "Read text and formatting from a placeholder.",
        "category": "Placeholders",
        "mutating": False,
        "params": [
            _pid(),
            _si(),
            _p("placeholder_name", "string", True, "Placeholder name"),
        ],
    },
    {
        "name": "pptx_set_placeholder_rich_text",
        "description": "Write multi-paragraph rich text into a placeholder.",
        "category": "Placeholders",
        "mutating": True,
        "params": [
            _pid(),
            _si(),
            _p("placeholder_name", "string", True, "Placeholder name"),
            _p(
                "paragraphs",
                "array",
                True,
                "Rich paragraph array",
                placeholder='[{"text": "Hello", "alignment": "center"}]',
            ),
        ],
    },
    {
        "name": "pptx_set_paragraph_spacing",
        "description": "Control line spacing and spacing before/after paragraphs.",
        "category": "Placeholders",
        "mutating": True,
        "params": [
            _pid(),
            _si(),
            *_shape_id_pair(),
            _p("paragraph_index", "number", True, "0-based paragraph index"),
            _p("line_spacing", "number", False, "Line spacing in points"),
            _p("space_before", "number", False, "Spacing before (points)"),
            _p("space_after", "number", False, "Spacing after (points)"),
        ],
    },
    # === Shapes ===
    {
        "name": "pptx_get_slide_shapes",
        "description": "Lightweight listing of all shapes on a slide.",
        "category": "Shapes",
        "mutating": False,
        "params": [_pid(), _si()],
    },
    {
        "name": "pptx_get_shape_details",
        "description": "Get detailed info about a shape by name or ID.",
        "category": "Shapes",
        "mutating": False,
        "params": [_pid(), _si(), *_shape_id_pair()],
    },
    {
        "name": "pptx_add_text_box",
        "description": "Add a free-form text box at specified position.",
        "category": "Shapes",
        "mutating": True,
        "params": [
            _pid(),
            _si(),
            _p("left", "measurement", True, "Left position", placeholder="1in"),
            _p("top", "measurement", True, "Top position", placeholder="1in"),
            _p("width", "measurement", True, "Width", placeholder="4in"),
            _p("height", "measurement", True, "Height", placeholder="1in"),
            _p("text_content", "string", False, "Simple text content"),
            _p(
                "paragraphs",
                "array",
                False,
                "Rich paragraphs (overrides text_content)",
                placeholder='[{"text": "Hello"}]',
            ),
            _p("alignment", "enum", False, "Alignment", enum_values=["left", "center", "right", "justify"]),
            _p("font_name", "string", False, "Font name"),
            _p("font_size_pt", "number", False, "Font size"),
            _p("bold", "boolean", False, "Bold"),
            _p("italic", "boolean", False, "Italic"),
            _p("color_hex", "string", False, "Font color"),
        ],
    },
    {
        "name": "pptx_add_shape",
        "description": "Add an auto-shape (rectangle, oval, arrow, etc.).",
        "category": "Shapes",
        "mutating": True,
        "params": [
            _pid(),
            _si(),
            _p(
                "shape_type",
                "enum",
                True,
                "Shape type",
                enum_values=[
                    "rectangle",
                    "rounded_rectangle",
                    "oval",
                    "diamond",
                    "triangle",
                    "right_arrow",
                    "left_arrow",
                    "up_arrow",
                    "down_arrow",
                    "pentagon",
                    "hexagon",
                    "chevron",
                    "star_5_point",
                    "cross",
                    "cloud",
                ],
            ),
            _p("left", "measurement", True, "Left", placeholder="1in"),
            _p("top", "measurement", True, "Top", placeholder="1in"),
            _p("width", "measurement", True, "Width", placeholder="2in"),
            _p("height", "measurement", True, "Height", placeholder="2in"),
            _p("fill_hex", "string", False, "Fill color hex"),
            _p("line_hex", "string", False, "Outline color hex"),
            _p("text", "string", False, "Text inside shape"),
        ],
    },
    {
        "name": "pptx_delete_shape",
        "description": "Remove a shape from a slide.",
        "category": "Shapes",
        "mutating": True,
        "params": [_pid(), _si(), *_shape_id_pair()],
    },
    {
        "name": "pptx_set_shape_text",
        "description": "Write text on any non-placeholder shape.",
        "category": "Shapes",
        "mutating": True,
        "params": [
            _pid(),
            _si(),
            *_shape_id_pair(),
            _p("text_content", "string", False, "Simple text"),
            _p("paragraphs", "array", False, "Rich paragraphs", placeholder='[{"text": "Hello"}]'),
        ],
    },
    {
        "name": "pptx_set_shape_properties",
        "description": "Modify position, size, rotation, fill, outline, name.",
        "category": "Shapes",
        "mutating": True,
        "params": [
            _pid(),
            _si(),
            *_shape_id_pair(),
            _p("left", "measurement", False, "Left position"),
            _p("top", "measurement", False, "Top position"),
            _p("width", "measurement", False, "Width"),
            _p("height", "measurement", False, "Height"),
            _p("rotation", "number", False, "Rotation in degrees"),
            _p("fill_hex", "string", False, "Fill color or 'none'"),
            _p("line_hex", "string", False, "Outline color or 'none'"),
            _p("line_width_pt", "number", False, "Outline width (pt)"),
            _p("name", "string", False, "New shape name"),
        ],
    },
    {
        "name": "pptx_clone_shape",
        "description": "Duplicate a shape with optional offset.",
        "category": "Shapes",
        "mutating": True,
        "params": [
            _pid(),
            _si(),
            *_shape_id_pair(),
            _p("target_slide_index", "number", False, "Target slide (defaults to same)"),
            _p("offset_left", "measurement", False, "X offset", placeholder="0.5in"),
            _p("offset_top", "measurement", False, "Y offset", placeholder="0.5in"),
        ],
    },
    {
        "name": "pptx_group_shapes",
        "description": "Group multiple shapes together.",
        "category": "Shapes",
        "mutating": True,
        "params": [
            _pid(),
            _si(),
            _p("shape_names", "array", False, "Array of shape names", placeholder='["Shape 1", "Shape 2"]'),
            _p("shape_ids", "array", False, "Array of shape IDs", placeholder="[1, 2]"),
            _p("group_name", "string", False, "Name for the group"),
        ],
    },
    {
        "name": "pptx_ungroup_shapes",
        "description": "Ungroup a group shape.",
        "category": "Shapes",
        "mutating": True,
        "params": [_pid(), _si(), *_shape_id_pair()],
    },
    {
        "name": "pptx_set_shape_z_order",
        "description": "Change visual layering of a shape.",
        "category": "Shapes",
        "mutating": True,
        "params": [
            _pid(),
            _si(),
            *_shape_id_pair(),
            _p("action", "enum", True, "Z-order action", enum_values=["front", "back", "forward", "backward"]),
        ],
    },
    {
        "name": "pptx_add_image",
        "description": "Add an image to a slide.",
        "category": "Shapes",
        "mutating": True,
        "params": [
            _pid(),
            _si(),
            _p("image_path", "path", True, "Absolute image file path"),
            _p("left", "measurement", False, "Left position", placeholder="0in"),
            _p("top", "measurement", False, "Top position", placeholder="0in"),
            _p("width", "measurement", False, "Width"),
            _p("height", "measurement", False, "Height"),
        ],
    },
    {
        "name": "pptx_add_line",
        "description": "Add a straight line between two points.",
        "category": "Shapes",
        "mutating": True,
        "params": [
            _pid(),
            _si(),
            _p("begin_x", "measurement", True, "Start X", placeholder="1in"),
            _p("begin_y", "measurement", True, "Start Y", placeholder="1in"),
            _p("end_x", "measurement", True, "End X", placeholder="5in"),
            _p("end_y", "measurement", True, "End Y", placeholder="3in"),
            _p("color_hex", "string", False, "Line color"),
            _p("width_pt", "number", False, "Line width (pt)"),
            _p("dash_style", "string", False, "Dash style: solid, dash, dot"),
            _p("line_name", "string", False, "Shape name for the line"),
        ],
    },
    {
        "name": "pptx_copy_shape_between_decks",
        "description": "Copy a shape between open presentations.",
        "category": "Shapes",
        "mutating": True,
        "params": [
            _p("source_presentation_id", "uuid", True, "Source presentation", auto_fill="presentation_id"),
            _p("source_slide_index", "number", True, "Source slide index"),
            *_shape_id_pair(),
            _p("target_presentation_id", "uuid", True, "Target presentation", auto_fill="presentation_id"),
            _p("target_slide_index", "number", True, "Target slide index"),
            _p("offset_left", "measurement", False, "X offset"),
            _p("offset_top", "measurement", False, "Y offset"),
        ],
    },
    {
        "name": "pptx_set_text_box_properties",
        "description": "Control margins, word wrap, auto-fit, vertical alignment.",
        "category": "Shapes",
        "mutating": True,
        "params": [
            _pid(),
            _si(),
            *_shape_id_pair(),
            _p("margin_left", "measurement", False, "Left margin"),
            _p("margin_right", "measurement", False, "Right margin"),
            _p("margin_top", "measurement", False, "Top margin"),
            _p("margin_bottom", "measurement", False, "Bottom margin"),
            _p("word_wrap", "boolean", False, "Word wrap"),
            _p(
                "auto_size",
                "enum",
                False,
                "Auto-size mode",
                enum_values=["none", "shape_to_fit_text", "text_to_fit_shape"],
            ),
            _p("vertical_alignment", "enum", False, "Vertical alignment", enum_values=["top", "middle", "bottom"]),
        ],
    },
    {
        "name": "pptx_set_shape_fill_gradient",
        "description": "Apply linear gradient to a shape.",
        "category": "Shapes",
        "mutating": True,
        "params": [
            _pid(),
            _si(),
            *_shape_id_pair(),
            _p("angle", "number", False, "Gradient angle (0-359)"),
            _p(
                "stops",
                "array",
                False,
                "Gradient stops",
                placeholder='[{"position": 0, "color_hex": "FF0000"}, {"position": 1, "color_hex": "0000FF"}]',
            ),
        ],
    },
    # === Tables ===
    {
        "name": "pptx_add_table",
        "description": "Create a table shape.",
        "category": "Tables",
        "mutating": True,
        "params": [
            _pid(),
            _si(),
            _p("rows", "number", True, "Number of rows"),
            _p("cols", "number", True, "Number of columns"),
            _p("left", "measurement", True, "Left", placeholder="1in"),
            _p("top", "measurement", True, "Top", placeholder="2in"),
            _p("width", "measurement", True, "Width", placeholder="8in"),
            _p("height", "measurement", True, "Height", placeholder="3in"),
            _p("data", "array", False, "Initial cell data [row][col]", placeholder='[["A","B"],["C","D"]]'),
        ],
    },
    {
        "name": "pptx_get_table",
        "description": "Read all cell content from a table.",
        "category": "Tables",
        "mutating": False,
        "params": [_pid(), _si(), *_shape_id_pair()],
    },
    {
        "name": "pptx_set_table_cell",
        "description": "Write text/formatting to a single cell.",
        "category": "Tables",
        "mutating": True,
        "params": [
            _pid(),
            _si(),
            *_shape_id_pair(),
            _p("row", "number", True, "0-based row"),
            _p("col", "number", True, "0-based col"),
            _p("text", "string", True, "Cell text"),
            _p("bold", "boolean", False, "Bold"),
            _p("italic", "boolean", False, "Italic"),
            _p("font_name", "string", False, "Font"),
            _p("font_size_pt", "number", False, "Size"),
            _p("color_hex", "string", False, "Font color"),
            _p("fill_hex", "string", False, "Cell fill color"),
        ],
    },
    {
        "name": "pptx_set_table_data",
        "description": "Batch-write entire table content.",
        "category": "Tables",
        "mutating": True,
        "params": [
            _pid(),
            _si(),
            *_shape_id_pair(),
            _p("data", "array", True, "2D array of cell values", placeholder='[["A","B"],["C","D"]]'),
        ],
    },
    {
        "name": "pptx_set_table_cell_merge",
        "description": "Merge a rectangular range of cells.",
        "category": "Tables",
        "mutating": True,
        "params": [
            _pid(),
            _si(),
            *_shape_id_pair(),
            _p("start_row", "number", True, "Start row (0-based)"),
            _p("start_col", "number", True, "Start col (0-based)"),
            _p("end_row", "number", True, "End row (0-based)"),
            _p("end_col", "number", True, "End col (0-based)"),
        ],
    },
    {
        "name": "pptx_set_table_style",
        "description": "Apply table styles (banding, header rows).",
        "category": "Tables",
        "mutating": True,
        "params": [
            _pid(),
            _si(),
            *_shape_id_pair(),
            _p("first_row", "boolean", False, "Header row emphasis"),
            _p("last_row", "boolean", False, "Total row emphasis"),
            _p("first_col", "boolean", False, "First column emphasis"),
            _p("last_col", "boolean", False, "Last column emphasis"),
            _p("banded_rows", "boolean", False, "Horizontal banding"),
            _p("banded_cols", "boolean", False, "Vertical banding"),
            _p("style_id", "string", False, "Table style GUID"),
        ],
    },
    # === Charts ===
    {
        "name": "pptx_add_chart",
        "description": "Add a chart to a slide.",
        "category": "Charts",
        "mutating": True,
        "params": [
            _pid(),
            _si(),
            _p(
                "chart_type",
                "enum",
                True,
                "Chart type",
                enum_values=[
                    "column_clustered",
                    "bar_clustered",
                    "line",
                    "pie",
                    "doughnut",
                    "area",
                    "xy_scatter",
                    "bubble",
                    "radar",
                ],
            ),
            _p("left", "measurement", False, "Left", placeholder="1in"),
            _p("top", "measurement", False, "Top", placeholder="1in"),
            _p("width", "measurement", False, "Width", placeholder="8in"),
            _p("height", "measurement", False, "Height", placeholder="5in"),
            _p("categories", "array", False, "Category labels", placeholder='["Q1", "Q2", "Q3"]'),
            _p("series", "array", True, "Series data", placeholder='[{"name": "Sales", "values": [10, 20, 30]}]'),
            _p("has_legend", "boolean", False, "Show legend"),
            _p(
                "legend_position",
                "enum",
                False,
                "Legend position",
                enum_values=["bottom", "corner", "left", "right", "top"],
            ),
            _p("has_data_labels", "boolean", False, "Show data labels"),
            _p("chart_style", "number", False, "Chart style number (1-48)"),
            _p("title", "string", False, "Chart title"),
        ],
    },
    {
        "name": "pptx_get_chart_data",
        "description": "Read chart data, type, and formatting.",
        "category": "Charts",
        "mutating": False,
        "params": [_pid(), _si(), *_shape_id_pair()],
    },
    {
        "name": "pptx_update_chart_data",
        "description": "Replace chart data preserving formatting.",
        "category": "Charts",
        "mutating": True,
        "params": [
            _pid(),
            _si(),
            *_shape_id_pair(),
            _p("categories", "array", False, "New categories", placeholder='["Q1", "Q2"]'),
            _p("series", "array", True, "New series data", placeholder='[{"name": "Sales", "values": [10, 20]}]'),
        ],
    },
    {
        "name": "pptx_set_chart_style",
        "description": "Modify chart legend, labels, title, style.",
        "category": "Charts",
        "mutating": True,
        "params": [
            _pid(),
            _si(),
            *_shape_id_pair(),
            _p("has_legend", "boolean", False, "Show legend"),
            _p(
                "legend_position",
                "enum",
                False,
                "Legend position",
                enum_values=["bottom", "corner", "left", "right", "top"],
            ),
            _p("has_data_labels", "boolean", False, "Show data labels"),
            _p("chart_style", "number", False, "Style number"),
            _p("title", "string", False, "Chart title (empty to remove)"),
        ],
    },
    # === Agent ===
    {
        "name": "pptx_agent_start",
        "description": "Start an AI agent task with a natural language query.",
        "category": "Agent",
        "mutating": False,
        "params": [
            _pid(),
            _p("query", "string", True, "Natural language transformation description"),
            _p("skip_questions", "boolean", False, "Skip clarifying questions"),
        ],
    },
    {
        "name": "pptx_agent_respond",
        "description": "Respond to agent clarifying questions.",
        "category": "Agent",
        "mutating": False,
        "params": [
            _p("task_id", "uuid", True, "Task ID from pptx_agent_start"),
            _p("answers", "array", True, "Answers array", placeholder='[{"question_id": "q1", "answer": "A"}]'),
        ],
    },
    {
        "name": "pptx_agent_execute",
        "description": "Execute the approved agent plan.",
        "category": "Agent",
        "mutating": True,
        "params": [
            _p("task_id", "uuid", True, "Task ID"),
            _p("confirm", "boolean", True, "Must be true to proceed"),
        ],
    },
    {
        "name": "pptx_agent_status",
        "description": "Get current state and progress of an agent task.",
        "category": "Agent",
        "mutating": False,
        "params": [
            _p("task_id", "uuid", True, "Task ID"),
        ],
    },
    {
        "name": "pptx_agent_rollback",
        "description": "Restore presentation to pre-execution state.",
        "category": "Agent",
        "mutating": True,
        "params": [
            _p("task_id", "uuid", True, "Task ID"),
        ],
    },
    {
        "name": "pptx_agent_cancel",
        "description": "Cancel an agent task and release resources.",
        "category": "Agent",
        "mutating": True,
        "params": [
            _p("task_id", "uuid", True, "Task ID"),
        ],
    },
    # === Checkers ===
    {
        "name": "pptx_check_positions",
        "description": "Check shapes for overlaps, out-of-bounds, and alignment.",
        "category": "Checkers",
        "mutating": False,
        "params": [
            _pid(),
            _p("slide_indices", "array", False, "Slides to check (default all)", placeholder="[1, 2]"),
            _p("check_overlaps", "boolean", False, "Check overlapping shapes (default true)"),
            _p("check_bounds", "boolean", False, "Check out-of-bounds (default true)"),
            _p("check_alignment", "boolean", False, "Check near-alignment (default false)"),
            _p("tolerance_px", "number", False, "Pixel tolerance (default 5)"),
        ],
    },
    {
        "name": "pptx_check_visual_consistency",
        "description": "Audit fonts, sizes, colors for inconsistencies.",
        "category": "Checkers",
        "mutating": False,
        "params": [
            _pid(),
            _p("slide_indices", "array", False, "Slides to check", placeholder="[1, 2]"),
            _p("check_fonts", "boolean", False, "Check font consistency (default true)"),
            _p("check_colors", "boolean", False, "Check color consistency (default true)"),
            _p("check_sizes", "boolean", False, "Check font size outliers (default true)"),
        ],
    },
    {
        "name": "pptx_check_content",
        "description": "Find empty placeholders and default template text.",
        "category": "Checkers",
        "mutating": False,
        "params": [
            _pid(),
            _p("check_empty_placeholders", "boolean", False, "Flag empty placeholders (default true)"),
            _p("check_default_text", "boolean", False, "Flag default template text (default true)"),
            _p("slide_indices", "array", False, "Slides to check", placeholder="[1]"),
        ],
    },
    {
        "name": "pptx_check_template_conformance",
        "description": "Compare against a reference template.",
        "category": "Checkers",
        "mutating": False,
        "params": [
            _pid(),
            _p("template_path", "path", True, "Reference template path"),
            _p("check_theme", "boolean", False, "Compare theme colors (default true)"),
            _p("check_fonts", "boolean", False, "Compare font schemes (default true)"),
            _p("check_layouts", "boolean", False, "Check layout existence (default true)"),
        ],
    },
    {
        "name": "pptx_diff_presentations",
        "description": "Generate before/after diff between two presentations.",
        "category": "Checkers",
        "mutating": False,
        "params": [
            _p("presentation_id_a", "uuid", True, "Before presentation ID", auto_fill="presentation_id"),
            _p("presentation_id_b", "uuid", True, "After presentation ID", auto_fill="presentation_id"),
            _p("deep_diff", "boolean", False, "Include per-shape text changes (default true)"),
        ],
    },
]


def get_catalog_by_category() -> dict[str, list[dict[str, Any]]]:
    """Return tools grouped by category, preserving insertion order."""
    groups: dict[str, list[dict[str, Any]]] = {}
    for tool in TOOL_CATALOG:
        cat = tool["category"]
        groups.setdefault(cat, []).append(tool)
    return groups
